workflowApi: "0.1"

# TODO: test this when we have actual event data
#inputs:
#  commit:
#    type: string

"on":
  push:
    branches:
      - master
      - stable-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - stable-*

jobs:
  greeter:
    steps:
      - uses: eladcon/shell-widget
        with:
          cmd: "echo hello standalone workflow test1, secret: '${{ secrets.TF_SECRETS_JSON }}'..."
          cmd2: "echo s... && exit 0"
