on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
    branches:
      - main
      - stable-*
jobs:
  greeter:
    steps:
      - using: eladcon/shell-widget
        with:
          cmd: echo The demo gods here is your donation
