"on":
  pull_request:
    branches:
      - master
      - stable-*
jobs:
  greeter:
    steps:
      - uses: eladcon/shell-widget
        with:
          cmd: echo The demo gods there is your $(cat ${{ secrets.secret1 }})
          
