"on":
  pull_request:
    branches:
      - master
      - stable-*
jobs:
  greeter:
    steps:
      - using: eladcon/shell-widget
        with:
          cmd: echo The demo gods there is your donation
