name: GitHub Actions Demo
# on: [push]
on:
  pull_request:
    branches:    
      - 'main'
      - 'releases/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event"
